name: Convert LaTeX to HTML and Generate Index

on:
  push:
    paths:
      - '**.tex'
      - '**/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore TeX Live cache
        id: cache-texlive
        uses: actions/cache@v3
        with:
          path: /usr/share/texlive
          key: texlive-2025-full

      - name: Install TeX Live manually (2025) if not cached
        if: steps.cache-texlive.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Find and convert LaTeX files to HTML
        run: |
          mkdir -p _converted
          for d in */ ; do
            texfile=$(find "$d" -maxdepth 1 -name "*.tex" | head -n 1)
            if [ -n "$texfile" ]; then
              name=$(basename "$texfile" .tex)
              mkdir -p "_converted/$d"
              make4ht -u -f html5 "$texfile" "mathjax"
              mv "$name.html" "_converted/$d/"
            fi
          done

      - name: Generate index.html with vCards
        run: |
          echo '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Project Index</title><style>body{font-family:sans-serif;background:#f9f9f9;padding:20px;} .card{background:#fff;border-radius:10px;padding:20px;margin:10px;box-shadow:0 0 10px rgba(0,0,0,0.1);} .card a{text-decoration:none;font-weight:bold;font-size:18px;color:#333;}</style></head><body><h1>Available Projects</h1>' > index.html
          REPO="${{ github.repository }}"
          USER=$(echo "$REPO" | cut -d'/' -f1)
          REPO_NAME=$(echo "$REPO" | cut -d'/' -f2)
          for d in _converted/* ; do
            projname=$(basename "$d")
            htmlfile=$(find "$d" -name "*.html" | head -n 1)
            if [ -n "$htmlfile" ]; then
              relative_path=$(echo "$htmlfile" | sed 's|^\./||')
              fullurl="https://$USER.github.io/$REPO_NAME/$relative_path"
              echo "<div class='card'><a href='$fullurl' target='_blank'>$projname</a></div>" >> index.html
            fi
          done
          echo '</body></html>' >> index.html

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add _converted index.html
          git commit -m 'Auto-convert LaTeX to HTML and update index' || echo "No changes to commit"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
