name: Build LaTeX Projects and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install TeX Live using specialized action with built-in caching
      - name: Install TeX Live
        uses: xu-cheng/texlive-action@v1
        with:
          packages: texlive-full tex4ht
          cache: true

      - name: Convert projects and build index
        run: |
          echo "Starting conversion process..."
          mkdir -p _site/_converted
          PROJECT_CARDS_HTML=""
          
          for dir in */; do
            dir_name=${dir%/}
            if [[ "$dir_name" == ".github" || "$dir_name" == "_site" ]]; then
              echo "Skipping utility directory: $dir_name"
              continue
            fi
            
            MAIN_TEX=$(find "$dir_name" -maxdepth 1 -type f -name "*.tex" | head -n 1)
            
            if [[ -n "$MAIN_TEX" ]]; then
              PROJECT_NAME=$(basename "$dir_name")
              echo "✅ Found LaTeX project: $PROJECT_NAME"
              
              # Add texlive binaries to PATH for current step
              export PATH="/usr/local/texlive/2023/bin/x86_64-linux:$PATH"
              
              make4ht -l -u -c ./build.cfg -d "_site/_converted/${PROJECT_NAME}" "$MAIN_TEX" "mathjax,svg"
              
              CARD="<a href=\"./_converted/${PROJECT_NAME}/\" class=\"block p-6 bg-white border border-gray-200 rounded-xl shadow-md hover:shadow-xl hover:scale-105 transition-all duration-300 ease-in-out\">
                <h3 class=\"mb-2 text-2xl font-bold tracking-tight text-gray-800\">${PROJECT_NAME}</h3>
                <p class=\"font-normal text-gray-500\">Click to view the converted HTML document.</p>
              </a>"
              PROJECT_CARDS_HTML="$PROJECT_CARDS_HTML $CARD"
            else
              echo "⚠️ No .tex file in: $dir_name"
            fi
          done
          
          sed "s|<!-- PROJECTS_LIST -->|${PROJECT_CARDS_HTML}|g" index.template.html > _site/index.html
          echo "✅ Site built successfully"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
